
####register
post http://localhost:1850/user/register
Content-Type: application/json

{
    "username": "Don",
    "email":"gordon2@gmail.com",
    "password": "@Qwerty123"
     
}


####login 

post http://localhost:1850/user/login
Content-Type: application/json

{    
    "email":"gordon2@gmail.com",
    "password": "@Qwerty123"
}

#####get user by id
get http://localhost:1850/user/b1d4367f-8696-4259-acb4-528ba5adbc31
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhbGViLmJhcmFrYUB0aGVqaXR1LmNvbSIsImlkIjoiMjhlNjFmNmUtZTgzOC00MWM3LWExNTUtMzgwYTg0ZDc4ODcxIiwiaWF0IjoxNzAwOTk0NTc1LCJleHAiOjE3MDEwODA5NzV9.-LbWQugUV9a0G3Uk5OAZBN3HGbijJU-R9XxsxSImIoY


#####get all users

get http://localhost:1850/user
token :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNsYXJlMSIsImVtYWlsIjoiY2xhcmUxQGdtYWlsLmNvbSIsIl9pZCI6ImIxZDQzNjdmLTg2OTYtNDI1OS1hY2I0LTUyOGJhNWFkYmMzMSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDI2MjkzNzksImV4cCI6MTcwMjcxNTc3OX0.qM8gyn9DD5ittVAJ2evHN4I6dyRUVbPY37LTrdBXFoU

#####update user

put http://localhost:1850/user
token :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNsYXJlMiIsImVtYWlsIjoiY2xhcmUyQGdtYWlsLmNvbSIsIl9pZCI6IjVhMGU3ZjA4LTUzYmYtNDkxMS05OGI1LTkyZGUxZmY3M2FhOSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDI2Mjk5MzIsImV4cCI6MTcwMjcxNjMzMn0.IEZqHwttKHvCNdL4rlJOzdN_yrID28mGNIBQM9kHHqs
Content-Type: application/json

{
    
    "_id":"28e61f6e-e838-41c7-a155-380a84d78871",
    "username": "clare",
    "email":"clare001@gmail.com"
}


##### delete user by ID
delete http://localhost:1850/user/28e61f6e-e838-41c7-a155-380a84d78871
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhbGViLmJhcmFrYUB0aGVqaXR1LmNvbSIsImlkIjoiMjhlNjFmNmUtZTgzOC00MWM3LWExNTUtMzgwYTg0ZDc4ODcxIiwiaWF0IjoxNzAwOTk0NTc1LCJleHAiOjE3MDEwODA5NzV9.-LbWQugUV9a0G3Uk5OAZBN3HGbijJU-R9XxsxSImIoY

### check user details
get http://localhost:1850/user/check_user_details
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJkaWFuYSIsImVtYWlsIjoiZGlhbmFhYmVyaTEyQGdtYWlsLmNvbSIsInVzZXJfaWQiOiJmODNjZjQ3MC0xYjc1LTQ0ZWMtYWRiNy03ZDZjMGRlZWJkOGIiLCJpc0FkbWluIjpmYWxzZSwiZnVsbE5hbWUiOiJEaWFuYSBhYmVyaSIsImlhdCI6MTcwMjQ1OTMxOSwiZXhwIjoxNzAyNTQ1NzE5fQ.zZ2M8ID5DAEyB64EmshP2bsvFX5ND5rjXDtvefEmCyE






### Create post 
POST http://localhost:1850/post/createPost
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbCIsImVtYWlsIjoiZGFuaWVsMkBnbWFpbC5jb20iLCJfaWQiOiI4Yzc5NzY1MS02OWVlLTRhYzMtOGNkOS1hOTg5YjE5ZTZjNjIiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzAyNjQzMjI4LCJleHAiOjE3MDI3Mjk2Mjh9.cVR0CcB4Lj2O8Dtao7LvB24bzHoVaK5UGYv3fXjgFio
Content-Type: application/json

{
    
    "created_by_user_id":"8c797651-69ee-4ac3-8cd9-a989b19e6c62",
    "caption":"My caption 333",
    "created_at":"1400hrs" ,
    "postImage":"https://images.unsplash.com/photo-1682685797898-6d7587974771?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"   
}


### update post 

PUT http://localhost:1850/post/editPost
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbCIsImVtYWlsIjoiZGFuaWVsMkBnbWFpbC5jb20iLCJfaWQiOiI4Yzc5NzY1MS02OWVlLTRhYzMtOGNkOS1hOTg5YjE5ZTZjNjIiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzAyNjQzMjI4LCJleHAiOjE3MDI3Mjk2Mjh9.cVR0CcB4Lj2O8Dtao7LvB24bzHoVaK5UGYv3fXjgFio
Content-Type: application/json

{
    "UpdatedPostImage":["https://c4.wallpaperflare.com/wallpaper/193/556/883/car-neon-chevrolet-corvette-race-cars-hd-wallpaper-preview.jpg","https://w0.peakpx.com/wallpaper/135/1018/HD-wallpaper-car-sports-car-neon-backlight-asphalt.jpg"],
    "updatedCaption":"This is my favorite caption",
    "post_id" : "a44e5190-1124-4776-9ee9-c70748765938",
     "updated_at" : "now"
}

### Delete post
DELETE http://localhost:1850/post/bb0a10b2-7524-4c8b-8177-d3e389f0f13c
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbCIsImVtYWlsIjoiZGFuaWVsMkBnbWFpbC5jb20iLCJfaWQiOiI4Yzc5NzY1MS02OWVlLTRhYzMtOGNkOS1hOTg5YjE5ZTZjNjIiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzAyNjQzMjI4LCJleHAiOjE3MDI3Mjk2Mjh9.cVR0CcB4Lj2O8Dtao7LvB24bzHoVaK5UGYv3fXjgFio
Content-Type: application/json

### Get Posts
GET http://localhost:1850/post
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbCIsImVtYWlsIjoiZGFuaWVsMkBnbWFpbC5jb20iLCJfaWQiOiI4Yzc5NzY1MS02OWVlLTRhYzMtOGNkOS1hOTg5YjE5ZTZjNjIiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzAyNjQzMjI4LCJleHAiOjE3MDI3Mjk2Mjh9.cVR0CcB4Lj2O8Dtao7LvB24bzHoVaK5UGYv3fXjgFio
Content-Type: application/json
### Get single Post 
GET http://localhost:1850/post/9629028b-b4b8-4a2f-beef-d424a0b9dcbe
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbCIsImVtYWlsIjoiZGFuaWVsMkBnbWFpbC5jb20iLCJfaWQiOiI4Yzc5NzY1MS02OWVlLTRhYzMtOGNkOS1hOTg5YjE5ZTZjNjIiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzAyNjQzMjI4LCJleHAiOjE3MDI3Mjk2Mjh9.cVR0CcB4Lj2O8Dtao7LvB24bzHoVaK5UGYv3fXjgFio
Content-Type: application/json












###  follow user
POST http://localhost:1850/FollowUser
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJkaWFuYSIsImVtYWlsIjoiZGlhbmFhYmVyaTEyQGdtYWlsLmNvbSIsInVzZXJfaWQiOiJmODNjZjQ3MC0xYjc1LTQ0ZWMtYWRiNy03ZDZjMGRlZWJkOGIiLCJpc0FkbWluIjpmYWxzZSwiZnVsbE5hbWUiOiJEaWFuYSBhYmVyaSIsImlhdCI6MTcwMjU4NjM0NSwiZXhwIjoxNzAyNjcyNzQ1fQ.q2f4tcavzwXBuyMrmusb7dioZ2oM3PqhzIQNkdXJHLA
Content-Type: application/json

{
   "following_id":"d83cf470-1b75-44ec-adb7-7d6c0deebd8b", 
   "followed_id":"d83cf470-1b75-44ec-adb7-7d6c0deebd8b"
}

#### get followers
GET http://localhost:1850/getFollowers/d83cf470-1b75-44ec-adb7-7d6c0deebd8b
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJkaWFuYSIsImVtYWlsIjoiZGlhbmFhYmVyaTEyQGdtYWlsLmNvbSIsInVzZXJfaWQiOiJmODNjZjQ3MC0xYjc1LTQ0ZWMtYWRiNy03ZDZjMGRlZWJkOGIiLCJpc0FkbWluIjpmYWxzZSwiZnVsbE5hbWUiOiJEaWFuYSBhYmVyaSIsImlhdCI6MTcwMjU4NjM0NSwiZXhwIjoxNzAyNjcyNzQ1fQ.q2f4tcavzwXBuyMrmusb7dioZ2oM3PqhzIQNkdXJHLA



### Get the followings/jesus
GET http://localhost:1850/getFollowings/d83cf470-1b75-44ec-adb7-7d6c0deebd8b
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJkaWFuYSIsImVtYWlsIjoiZGlhbmFhYmVyaTEyQGdtYWlsLmNvbSIsInVzZXJfaWQiOiJmODNjZjQ3MC0xYjc1LTQ0ZWMtYWRiNy03ZDZjMGRlZWJkOGIiLCJpc0FkbWluIjpmYWxzZSwiZnVsbE5hbWUiOiJEaWFuYSBhYmVyaSIsImlhdCI6MTcwMjU4NjM0NSwiZXhwIjoxNzAyNjcyNzQ1fQ.q2f4tcavzwXBuyMrmusb7dioZ2oM3PqhzIQNkdXJHLA

